apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openldap-openldap-stack-ha
  namespace: openldap
spec:
  encryptedData:
    LDAP_ADMIN_PASSWORD: AgAnrxVttfEeameFweeXF+f13y/z5Qle6YMFRDIVwULDPjT46b87gGmQtwC0za0cSS7s2oCujEbrxRP+edpP9E+7J7syxPSOnWf1lruQXNspujGsniGhpW8lE1xKLekNZw/S3xZQDyo0XPEiw04F4zFgt2yQharFcbZNB9jydK2n7ibsMmSqQMUjFqDOc5OsY/fzSR81dyOdUoJceMAIwyQecT4bXLa/+v+wcOb5V2rjEx/5w9ubVvKbxU3l887oGW4SUvDBnsgzuKvan7/kbs++qcW2BdCDx/O5d8R3eFpHQ78vXQJCiCQG5fsk9SUtUcq77uviuFr3LEvq774bsIVGDh6QS1h+BcOqt1vNCFbb0jWS5fCiTSGGMbSEgOvDltYb0UbMsjKe7GszzmfrPoLGXwURB5cVKBTCOQAMsmyz5hQOydvz4hFMQ6rMzLZixCQzMXhmPhZIHBLf3HyI3kP1sutGkI+BhC83uBE+vzcEMRu1JbugVS+G+cf1euG8yhmi9AhCDoY6kbB0h9iU5TzFlH3wExN2XRsXU9WH2sjTU8Mqwhe2859N+6aYL87pV8fpGH5ctlAqrLdJhksF7FFKkFj4mHc4MpNaDQQGrU19EJqV8P0cJEMU1jA/lyIIVxScLGKpmM4TqlRu4SeiAredXsS1HR0vDTWs04d8F3IWOB0MegPMOHAuudWx2Ftb5SN4V793p/xnLA==
    LDAP_CONFIG_PASSWORD: AgBYUUOzK1M8CsMj4ya7CvFxkpdVv0D0D0dYH2ErdAItCJdG8ig/bWhpFjvHTAXGuXiFRjFcdwf5jxL5E0m23HIen3pmgrcpMyWVaKTR5U2JkKRjwjh2yZ9/2ufhC00urX5zoDItR35ED7PXTWViv4Gj+/bSth1taF28BMVI0EGLhmytB7kM5QBwj0sDp4cPVrO348i6qW6d4QPgprmbQ+mufAQGzZIMqOPd0gKCM0cV2huquPHUFO9xGRwhTZyrrFp73pUUBLHHiGY87HMggl+j9P0ZPzkyE4LA8y9XIy3/MxFeVUnhrCIfWwpijgtw3S753Ag+AgFye2HuBL04JYkX2f2zePXl25wZQagj2jkd0TUJjtWdS61rvTzmRvTyrO0v6JhZIG3vfZD1zqQLq2z/wDhyJHMhY9wWjr6fD4ljoYz79k9CqRbNEQluba7iAr7qxzHTO+S1HCLdRcW50fAGJx2NzSZTLLWdm7k5FWTZHcWf2hb26NZdPb6MAY85qMXODakHdsROmHr19h779czemkDUqdBCtrIcXaZkY/kWd6umucxV2Uhy1zWx4e8A6ZScefTpwGosaLBEa8m3RzmrUkzZ6bJ0JrcAnMYfGj8zDERiIqRRxQamVyrlMr3ygzSmJxvtg3+K/LwWuRhqxx3rYe/E1Yc299Jf5D5crX6d+REU1CfntIMVPohBWPoPOvdla8vdQycHFg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "205"
      creationTimestamp: null
      name: openldap-openldap-stack-ha
      namespace: openldap
    type: Opaque

