apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openldap-openldap-stack-ha
  namespace: openldap
spec:
  encryptedData:
    LDAP_ADMIN_PASSWORD: AgBoUHZ4RCB4oODFZWuOFJmpmd9g7njhgUNk99fCh8dwbSV+ULfhb+rfaOApvHzW/m3bW5ftoHyfF6iDnduet34kvwcv1Tywg9rB4LoRhcxueKnAkw88Ez6xEyyCjqBEwlw53dW49cItAhF6FSjm9KlOwVz4UF/WqAnCFizfTXRMjzZrQQXrY+k/ERaQMDLQ25umegDOEmUK4/ydouhfZoe4i0XxyY63UgHcAHNJtcdFu4ge5qWRofYA1IkLQJNXQIvMtQRMd8k2yPP2okuFUvj2Dtfw8c89l8ontNcR5IN18NTYIVT86dUR/Uqnn1+/cT/dohBgZ2Qsx8VkVM+jvVqaAipNIQ73dp3+R+p6W12PBEua7XX2ekBBFumT/Y7T7k8AFcPXHaAsHODU5XvtMfwMOMIteqiB7ECcynY7pbWiCzp60RzcFtyFg4nRdSxERyufLS+p98+utZlIiLDPkwBIxxcyWx3VWyEu8t7TDLtUMT/QVl84bcPc5Zt/6ztVxFWPAVKHLGGLV49p8p69R8FO/cPLE7wZIhdM+XTvzyAehNTxb3aLbjqdIHXWiuw+1KGxgPs8/fDA+y2DZgtoXxfOpbHQcqevqfBD5aNLLhEWEF3JuI2lnY/uWOBZbygPtU9S1klvBCflCpCnIkDGVX5zfN4mACZ0QwLqEFW7dZiLcIncXEntYdI5qzwKZJIWXXt8uAGwUjcZ7g==
    LDAP_CONFIG_PASSWORD: AgAxbczT9v3oS1QeslzQRUrJGFqOygxlybsqGXqqNnKBjhHu2OKtbC4zS1feOmye3z8EP6fD0aR+OrOjwBCv9hlVWxShz1n8BYG1yfigbYGk3LpbOX5DO+pZWBkGIQMRCMmDhfJv/JWZhXQIBEuZI+iBI85dczHNFohp8A5saUy+4WsSGRr+mwjqoQgpUY4U6Frq4UwKOaIswJR6VGBqeWIBB06eLaan814awVCj6Z3WGIl+GspN4QZC4Ec5ZOaDnIoBcOrRz5VMkkKhMzbTM4ZD8ZlXjEilHRE/EhG/QZRLi9CB7lFWnVyUMtdqJL4zqFJMm5ZCK+TB3Zq/i7bBaht897VMnbjkkQpd81MNU9dJqU84ChTDEyYmHSun1yiKf6ZczsAn0l1X2WKznvJtyl2TRDvkGxZGXZ7CqoKHOfDLeelvsfIVqVMWY/ej11RCCf4N1iE5XYLjLldxfuW62P8lcII46Xj4DbTZiK/wgV9mtHqBGM9W0qizvbxz/d0uOlFBNDPzXbaixgcVHfgLllctkKe8Bq+jOaRXZ69k+B7hFEoEhMOeQtnj3Fnd+3Ly6A0Zh/DcKSgJxtwkufH7FGc3bEaX3oHhJFkK1nAzGiNgWXM4l/K+sZcObGgTVoljTowJyNuV7nDxc0856aIjueE/NSClwqTgLdKEmkl1Pj/rAOi9bBJu2INooNsB2kp/SkaakB9F4ay+Kg==
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "205"
      creationTimestamp: null
      name: openldap-openldap-stack-ha
      namespace: openldap
    type: Opaque

