apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openldap-ltb-passwd
  namespace: openldap
spec:
  encryptedData:
    LDAP_ADMIN_PASSWORD: AgCcVQZFBpj8fGH3P5hv7UPDydBJ5lcZ2g/P5k8QCprkf6J+6ViHwsKs/TAeMaKDBDBzA8QfeoUR+qHX0CY/5Y7OBjnOT/g9FvTAywseBn9FsE7B8DichFT+QI1gDI1NL5MxWupZdcVTpq4effPKQP1Q31Q7dKs6O2/pYFb5SMzDr6SPFlc3hCPXJeNzrkvcdprtTc3LLiFjzQbVmWpIINHI0wLAy5Bi3H6XVZ3wbuSiUXKnJDHF3SHzlO6osmU97pgtzd3b+nmYMbMZsvqE+488TQ1b/gLdl1aPAcyaSy+osyrA3Tpyi/JA4oFecqAdgxPpoZsKYOp8ceI6KPOYly0kv7h1axPTYMyh6N+7R5ZtYkqT5/sEVdZQ2HVSnn+GnR+RM2GrD/ifuIb8EC7aglSHR2tAQapskGGb07N2/TSOAbtOP7qFXCsnmqsoJ2F31E03qpTPvPsi4BcVN0Xuds+yZbfSCj9V6chqrpkeToI6i2Q0z0FCTRz2WDCJdDm8csCxTxpfrUGex8Y+fi/lBe/mfDuN4nOrlcl3DXGNIDOnweW6VPRIzggYopnvmNoHiijPR2BAB6D8QZ7Jfv/zZ6KkhyJ6V42hUd1uSpzCbes4ApP4bOoqOwSYyd/B+SaY3q0QNhnzdHDB9pLubCHOsCoTD0qfisbcztuGxrs9oy0PmS8jre1Pp+dHA71SuzMdqWnzsAmJU2SLLw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "205"
      creationTimestamp: null
      name: openldap-ltb-passwd
      namespace: openldap
    type: Opaque

